### ISSUE TITLE
New image loads in emulation, hangs on real hardware

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-8-bit-OS#36]
I compiled the OS + ROMdisk, producing **os_with_romdisk.img**, which loads and runs flawlessly in the emulator. However, after flashing the board with the same image, the computer hangs while booting the new OS.

The image is available [here](https://github.com/Candid-Moe/Zorth/blob/main/os_with_romdisk.img). It's configured to boot and run `zorth.bin`.

This is the dialog in the bootloader section (57.600, 8 bit, 1 stop bit, no parity):

```
Zeal 8-bit Computer bootloader v1.2.1
...
Enter your choice: a
Numbers must be provided in hexadecimal
New entry name (max 32 chars): Zorth
22-bit physical address, aligned on 16KB: 4000
16-bit virtual address: 0


Entering menu. Please select an option:

1 - Boot Zeal 8-bit OS (0x004000 -> 0x0000)
2 - Boot Zorth (0x004000 -> 0x0000)
p - Load program from UART
a - Add a new entry
d - Delete an existing entry
s - Save configuration to flash
b - Change baudrate
f - Flash/Program the ROM
q - Quick format I2C EEPROM (ZealFS)
t - Test hardware

Enter your choice: f
Numbers must be provided in hexadecimal
ROM address to flash, aligned on 4KB: 4000
Binary size: c70d
Please, send file...
Flashing in progress, do not turn off...


Entering menu. Please select an option:

1 - Boot Zeal 8-bit OS (0x004000 -> 0x0000)
2 - Boot Zorth (0x004000 -> 0x0000)
p - Load program from UART
a - Add a new entry
d - Delete an existing entry
s - Save configuration to flash
b - Change baudrate
f - Flash/Program the ROM
q - Quick format I2C EEPROM (ZealFS)
t - Test hardware

Enter your choice: 2

Now booting Zorth



```
That is as after as it goes.

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe !

From what you tell me, I suspect your bootloader is using the UART as the standard output (since you specified the baudrate config).

When I execute the OS image you linked in the emulator, the text output is on the video, not the UART. So, it normal that the bootloader doesn't have any further output after booting Zorth, since the latter will have its output on the video board.

If you have the video board, do you have any output on the video output?
If you don't have the video board, you will want to recompile the OS with the UART as the standard output.

**Comment by Candid-Moe** [comment]
No, I don't have the video board. Some day ...

Well, I changed the standard output driver to UART, recompiled it and upload. I got stucked:
![Screenshot at 2024-08-14 07-21-05](https://github.com/user-attachments/assets/faecbc86-a4a0-43d7-a891-56537baccdde)

I tested with "executable to launch on bot" set to "a:zorth.bin" y "a:init.bin", with same results.

BTW, it's "init.bin" included by default in the rom disk?

**Comment by Zeal8bit** [comment]
@Candid-Moe I see, then the way you recompiled the OS is correct. You may want to check the following:
* In the path of the binary to launch, you forgot the `/`, it should be `A:/zorth.bin`.
* Make sure to modify the `Physical address of the kernel` option in the menuconfig to `0x4000` in your case (because the romdisk will be flashed at NOR flash 0x4000) 
* The files to include in the romdisk by default are set in `romdisk/Makefile`. User files to be put in romdisk can be specified with the environment variable `EXTRA_ROMDISK_FILES`.

**Comment by Candid-Moe** [comment]
I can't boot any image. I did `make clean; make menuconfig; make`, changing only standard output to UART. No extra files for the romdisk, and still can't pass the same point.

**Comment by Zeal8bit** [comment]
@Candid-Moe You also need to modify the `Physical address of the kernel` option to `0x4000` since this is where you will flash the OS image, then it should be enough to have the system boot directly into `zorth.bin` or `init.bin`

**Comment by Candid-Moe** [comment]
Still the same result with this parameters

![Screenshot at 2024-08-15 05-28-05](https://github.com/user-attachments/assets/12d5f259-a78d-45e4-a640-1ddcf6e14cd1)

**Comment by Zeal8bit** [comment]
@Candid-Moe Can you please try the following ROM: https://zeal8bit.com/roms/staging/os_with_zoth.img

Flash it at address 0x4000, it was compiled with the following configuration: https://zeal8bit.com/roms/staging/os.conf

If it still doesn't work, I highly suspect the program you use on your host computer to send the rom via UART is corrupting the file (it adds a header maybe? Or it shifts some bytes? Converts the `0xA` bytes into `0xD` `0xA`?)

**Comment by Candid-Moe** [comment]
The ROM link gave me a 404, but I copied your os.conf and recompiled it. Now it's working !
![Screenshot at 2024-08-15 11-36-24](https://github.com/user-attachments/assets/b12abeed-f53a-41cc-a7a0-15cf2ba7b192)
The only difference in your os.conf seems to be that mine line

`CONFIG_TARGET_ENABLE_VIDEO=y`

has been commented out. I didn't find the corresponding control in menuconfig for this variable.

**Comment by Zeal8bit** [comment]
@Candid-Moe Any r was missing in the URL I edited it.

Glad to hear it worked! This video option can be disabled in the "Zeal 8-bit Computer" sub menu, "Enable video driver"

**Comment by Zeal8bit** [comment]
@Candid-Moe I was able to identify and fix the bug, thanks again for reporting it!
